# Generated by Django 3.0.5 on 2020-05-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20200501_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origemsregistros',
            options={'verbose_name_plural': 'CATEGORIAS'},
        ),
    ]
