# Generated by Django 3.0.5 on 2020-05-30 00:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0003_auto_20200512_1859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entradas',
            unique_together={('usuario',)},
        ),
    ]
