# Generated by Django 3.0.5 on 2020-05-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_entradas_saidas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradas',
            options={'verbose_name_plural': 'ENTRADAS'},
        ),
        migrations.AlterModelOptions(
            name='lancamentoconta',
            options={'verbose_name_plural': 'LANCAMENTO DE CONTAS'},
        ),
        migrations.AlterModelOptions(
            name='saidas',
            options={'verbose_name_plural': 'SAIDAS'},
        ),
    ]
