# Generated by Django 3.0.5 on 2020-06-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20200530_0032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entradas',
            unique_together=set(),
        ),
    ]
