# Generated by Django 3.0.5 on 2020-05-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_remove_lancamentoconta_lembrar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamentoconta',
            old_name='usuario',
            new_name='user',
        ),
    ]
